name: firecrawl

services:
  api:
    image: trieve/firecrawl
    build: apps/api
    networks:
      - backend
    environment:
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - REDIS_RATE_LIMIT_URL=${REDIS_URL:-redis://redis:6379}
      - PORT=${PORT:-3002}
      - BULL_AUTH_KEY=${BULL_AUTH_KEY}
      - TEST_API_KEY=${TEST_API_KEY}
      - HOST=${HOST:-0.0.0.0}
      - LOGGING_LEVEL=${LOGGING_LEVEL}
      - MAX_RAM=${MAX_RAM:-0.95}
      - MAX_CPU=${MAX_CPU:-0.95}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
    ports:
      - "3002:3002"
    command: ["pnpm", "run", "start:production"]

  redis:
    image: redis:alpine
    networks:
      - backend
    command: redis-server --bind 0.0.0.0

networks:
  backend:
    driver: bridge
